'use strict';function f(a){throw a;}var i=void 0,j=!0,k=null,n=!1;function aa(a){return function(){return this[a]}}var p,ba=this;Math.floor(2147483648*Math.random()).toString(36);function q(a,b){var c=a.split("."),d=ba;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==i?d[e]=b:d=d[e]?d[e]:d[e]={}}function v(a,b){function c(){}c.prototype=b.prototype;a.yb=b.prototype;a.prototype=new c};function ca(a,b){this.x=a!==i?a:0;this.y=b!==i?b:0}ca.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function da(a,b){this.x=a;this.y=b}v(da,ca);da.prototype.scale=function(a){this.x*=a;this.y*=a;return this};da.prototype.rotate=function(a){var b=Math.cos(a),a=Math.sin(a),c=this.y*b+this.x*a;this.x=this.x*b-this.y*a;this.y=c;return this};var ea,fa;HTMLCanvasElement.Xa=new da(0,0);function ga(a){var b=x,c=HTMLCanvasElement.Xa;c.x=0;c.y=0;b.ha===i&&(b.ha=$(b).offset(),b.Wa=$(b).height());c.x=a.pageX-b.ha.left;c.y=b.Wa-(a.pageY-b.ha.top);return c}
(function(){for(var a=0,b=["ms","moz","webkit","o"],c=0;c<b.length&&!window.requestAnimationFrame;++c)window.requestAnimationFrame=window[b[c]+"RequestAnimationFrame"],window.Ba=window[b[c]+"CancelAnimationFrame"]||window[b[c]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(console.log("using setTimeout"),window.requestAnimationFrame=function(b){var c=Date.now(),g=Math.max(0,16-(c-a)),h=window.setTimeout(function(){b(c+g)},g);a=c+g;return h});window.Ba||(window.Ba=function(a){clearTimeout(a)})})();
function ha(a,b){console.log(WebGLDebugUtils.glEnumToString(a)+" was caused by call to "+b)}var ia={useGoogleAnalytics:n,projection:"3d",webglMode:j,usesOffscreenBuffer:n,basePath:"",debugSpanId:"debug-info"},ja="3d",y=j,ka=n,la=n,ma="",C=k,na=n,oa={},pa=k,qa=k,ra=k,x=k,sa=n,D={},E={},ta={},ua={},va=Date.now(),wa=0,xa=k,ya={sb:0,vb:1,wb:2,tb:3,ub:4},G=[];function za(a){var b=oa[a],c=C;if(a!=pa){pa=a;c.validateProgram(b);c.useProgram(b);for(var d in b.a)c.enableVertexAttribArray(b.a[d])}return b}
function Aa(){var a=x;C.V=a.width;C.P=a.height}
function Ca(){var a=C;Da("default",function(b){b.u=a.getUniformLocation(b,"uMVPMatrix");b.a={vertexPositionAttribute:a.getAttribLocation(b,"aVertexPosition"),vertexColorAttribute:a.getAttribLocation(b,"aVertexColor")};b.mvpMatrixUniform=b.u;b.attribs=b.a});Da("texture",function(b){b.u=a.getUniformLocation(b,"uMVPMatrix");b.ua=a.getUniformLocation(b,"uSampler");b.a={vertexColorAttribute:a.getAttribLocation(b,"aVertexColor"),textureCoordAttribute:a.getAttribLocation(b,"aTextureCoord"),vertexPositionAttribute:a.getAttribLocation(b,
"aVertexPosition")};b.mvpMatrixUniform=b.u;b.samplerUniform=b.ua;b.attribs=b.a})}
function Da(a,b){var c=C,d=Ea(a,"frag"),e=Ea(a,"vert"),g=c.createShader(c.FRAGMENT_SHADER);c.shaderSource(g,d);c.compileShader(g);c.getShaderParameter(g,c.COMPILE_STATUS)?(d=c.createShader(c.VERTEX_SHADER),c.shaderSource(d,e),c.compileShader(d),c.getShaderParameter(d,c.COMPILE_STATUS)?(c=C,e=c.createProgram(),c.attachShader(e,g),c.attachShader(e,d),c.linkProgram(e),c.getProgramParameter(e,c.LINK_STATUS)||console.log("problem linking shader"),oa[a]=e,b&&b(e)):console.log("problem compiling vertex shader "+
a+"("+c.getShaderInfoLog(d)+"):\n"+e)):console.log("problem compiling fragment shader "+a+"("+c.getShaderInfoLog(g)+"):\n"+d)}function Ea(a,b){var c="";$.ajax({url:ma+"shaders/"+a+"."+b,async:n,type:"GET",success:function(a,b){"success"==b?c=a:console.log("error getting the shader data")}});return c}
function H(a,b,c){var d=i;"object"==typeof b&&(d=b.dataType,b=b.path);D[a]||(D[a]={});var e=D[a];if(e[b])if("loading"==e[b].status)c&&e[b].S.push(c);else if("loaded"==e[b].status)c&&c(e[b].data);else{if("try"==e[b].status){e[b].status="loading";if(ta[a])ta[a](a,{url:b,dataType:d});else ta["default"](a,{url:b,dataType:d});c&&e[b].S.push(c)}}else e[b]={data:k,status:"try",S:[]},c&&e[b].S.push(c),H(a,{path:b,dataType:d})}
function Fa(a,b){var c=ua[a];c||(ua[a]=[],c=ua[a]);b&&c.push(b);var d=j;if("all"==a)for(var e in D){var g=D[e],h;for(h in g)if("loaded"!=g[h].status){d=n;break}if(!d)break}else for(h in g=D[a],g)if("loaded"!=g[h].status){d=n;break}if(d)for(;d=c.shift();)d()}function Ga(a,b){return b?D[a][b].data:k}function Ha(a,b,c){D[c][a].data=b;return j}
function Ia(a,b){y&&!b.U&&(b.U=C.createTexture());D.texture[a].data=b;var c;if(y){c=C;var d=j;try{var e=0;c.pixelStorei(c.UNPACK_FLIP_Y_WEBGL,1);c.activeTexture(c.TEXTURE0);c.bindTexture(c.TEXTURE_2D,b.U);c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,b);e=c.getError();0!==e&&(console.log("gl error "+e),d=n);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MAG_FILTER,c.NEAREST);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_S,c.CLAMP_TO_EDGE);
c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_T,c.CLAMP_TO_EDGE);c.bindTexture(c.TEXTURE_2D,k)}catch(g){console.log("got some error: "+g),d=n}c=d}else c=j;return c}function Ja(a,b){var c=new Image,d=b.url;c.addEventListener("load",function(){var b=D.texture[d];if(E[a](d,c)){b.status="loaded";for(var g;g=b.S.shift();)g(b.data);Fa(a);Fa("all")}else b.status="try",H(a,d)},n);d.match(/^http(s)?:\/\//)?(c.crossOrigin="anonymous",c.src=d):(c.crossOrigin="anonymous",c.src=ma+d)}
function Ka(a,b){var c=b.url,d=c;c.match(/^http(s)?:\/\//)||(d=ma+c);$.ajax({url:d,dataType:b.dataType,xb:function(a){a.withCredentials=j},success:function(b,d){var h=D[a][c];if("success"==d)if((E[a]||E["default"])(c,b,a)){h.status="loaded";for(var m;m=h.S.shift();)m(h.data);Fa(a);Fa("all")}else h.status="try",H(a,c);else console.log("Error loading asset "+c)}})}
function Ua(){var a=i;y?(a=C,a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT)):(a=fa,a.setTransform(1,0,0,1,0,0),a.fillRect(0,0,a.V,a.P));ra&&ra.A();!y&&ka&&(a.fillRect(0,0,a.V,a.P),a.drawImage(ea,0,0));a=Date.now();wa=a-va;va=a}var Va=Date.now(),Wa=0,Xa=0,Ya=0,Za=0,$a=0,K=new Float32Array(3);function ab(a){var a=ga(a),b=0,c=G.length;for(K.set([a.x,a.y,0]);b<c;b++)G[b](K,0)}function bb(a){var a=ga(a),b=0,c=G.length;for(K.set([a.x,a.y,0]);b<c;b++)G[b](K,1)}
function cb(a){var a=ga(a),b=0,c=G.length;for(K.set([a.x,a.y,0]);b<c;b++)G[b](K,2)}function db(a){var a=ga(a),b=0,c=G.length;for(K.set([a.x,a.y,0]);b<c;b++)G[b](K,3)}function eb(a){var a=ga(a),b=0,c=G.length;for(K.set([a.x,a.y,0]);b<c;b++)G[b](K,4)}
function fb(){if(!na){window.requestAnimationFrame(fb,x);Ua();L.nb(wa);var a=Date.now();Wa+=wa;Xa++;if(1E3<a-Va){var b=Wa/Xa;$a=1*b;Za+=b;Ya++;xa&&(xa.textContent=b.toFixed(2));ra&&(la&&5<Ya)&&(_gaq.push(["_trackEvent","chesterGL","renderTime-"+y+"-0.3",ra.title,1*(Za/Ya)]),Za=Ya=0);Wa=Xa=0;Va=a}}}q("chesterGL.version","0.3");q("chesterGL.settings",ia);q("chesterGL.mouseEvents",ya);ya.UP=2;ya.DOWN=0;ya.MOVE=1;ya.ENTER=3;ya.LEAVE=4;q("chesterGL.getSampledMpf",function(){return $a});
q("chesterGL.viewportSize",function(){return new O(C.V,C.P)});
q("chesterGL.setup",function(a){a=document.getElementById(a);ja=ia.projection;y=ia.webglMode;la=ia.useGoogleAnalytics;ka=ia.usesOffscreenBuffer;ma=ia.basePath;try{if(x=a,y&&(C=a.getContext("experimental-webgl",{alpha:n,antialias:n,preserveDrawingBuffer:j}))&&window.WebGLDebugUtils)console.log("installing debug context"),C=WebGLDebugUtils.makeDebugContext(C,ha)}catch(b){console.log("ERROR: "+b)}C||(C=a.getContext("2d"),ka?(ea=document.createElement("canvas"),ea.width=a.width,ea.height=a.height,fa=
ea.getContext("2d"),fa.V=a.width,fa.P=a.height):fa=C,(!C||!fa)&&f("Error initializing graphic context!"),y=ia.webglMode=n);Aa();$(x).mousedown(ab);$(x).mousemove(bb);$(x).mouseup(cb);$(x).mouseenter(db);$(x).mouseleave(eb);y&&Ca();var a=window.location.search.substring(1).split("&"),c;for(c in a){var d=a[c].split("=");"_cdbg"==d[0]&&"1"==d[1]&&(sa=j,console.log("debug mode on"))}xa=document.getElementById("debug-info");E.texture=Ia;E["default"]=Ha;ta.texture=Ja;ta["default"]=Ka});
q("chesterGL.canvasResized",Aa);q("chesterGL.initShader",Da);q("chesterGL.registerAssetHandler",function(a,b){E[a]=b});q("chesterGL.loadAsset",H);q("chesterGL.assetsLoaded",Fa);q("chesterGL.getAsset",Ga);
q("chesterGL.setupPerspective",function(){var a=C;if(y){a.clearColor(0,0,0,1);a.blendFunc(a.SRC_ALPHA,a.ONE_MINUS_SRC_ALPHA);a.enable(a.BLEND);a.disable(a.DEPTH_TEST);var b=a.V,c=a.P;a.viewport(0,0,b,c);qa=gb();if("2d"==ja)console.log("setting up 2d projection ("+b+","+c+")"),hb(qa,2/(b-0),0,0,0,0,2/(c-0),0,0,0,0,-2/2048,0,-(b+0)/(b-0),-(c+0)/(c-0),-0.0,1);else if("3d"==ja){console.log("setting up 3d projection ("+b+","+c+")");var d=c/1.1566;var a=gb(),e=b/c,g=60*Math.PI/180/2,h=Math.sin(g);0==h||
0==e||(g=Math.cos(g)/h,hb(a,g/e,0,0,0,0,g,0,0,0,0,-1500.5/1499.5,-1,0,0,-1500/1499.5,0));d=[b/2,c/2,d];e=[b/2,c/2,0];b=gb();c=ib[0];c[0]=e[0]-d[0];c[1]=e[1]-d[1];c[2]=e[2]-d[2];jb(c,c);c[3]=0;e=ib[1];kb(c,[0,1,0],e);jb(e,e);e[3]=0;g=ib[2];kb(e,c,g);jb(g,g);g[3]=0;c[0]=-c[0];c[1]=-c[1];c[2]=-c[2];lb(b,0,e);lb(b,1,g);lb(b,2,c);b[3]=0;b[7]=0;b[11]=0;b[15]=1;mb(b,-d[0],-d[1],-d[2]);nb(a,b,qa)}else f("Invalid projection: "+ja)}});q("chesterGL.setRunningScene",function(a){a.type==P.SCENE&&(ra=a)});
q("chesterGL.drawScene",Ua);q("chesterGL.run",fb);q("chesterGL.togglePause",function(){na?(na=n,va=Date.now(),fb()):na=j});q("chesterGL.isPaused",function(){return na});q("chesterGL.addMouseHandler",function(a){-1==G.indexOf(a)&&G.push(a)});q("chesterGL.removeMouseHandler",function(a){a=G.indexOf(a);0<a&&G.splice(a,1)});function O(a,b){this.width=a;this.height=b}O.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};O.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};O.prototype.scale=function(a){this.width*=a;this.height*=a;return this};function Q(a){this.length=a.length||a;for(var b=0;b<this.length;b++)this[b]=a[b]||0}Q.prototype.BYTES_PER_ELEMENT=8;Q.prototype.set=function(a,b){for(var b=b||0,c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};Q.prototype.toString=Array.prototype.join;"undefined"==typeof Float64Array&&(Q.BYTES_PER_ELEMENT=8,Q.prototype.BYTES_PER_ELEMENT=Q.prototype.BYTES_PER_ELEMENT,Q.prototype.set=Q.prototype.set,Q.prototype.toString=Q.prototype.toString,q("Float64Array",Q));function R(a){this.length=a.length||a;for(var b=0;b<this.length;b++)this[b]=a[b]||0}R.prototype.BYTES_PER_ELEMENT=4;R.prototype.set=function(a,b){for(var b=b||0,c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};R.prototype.toString=Array.prototype.join;"undefined"==typeof Float32Array&&(R.BYTES_PER_ELEMENT=4,R.prototype.BYTES_PER_ELEMENT=R.prototype.BYTES_PER_ELEMENT,R.prototype.set=R.prototype.set,R.prototype.toString=R.prototype.toString,q("Float32Array",R));function ob(a){var b=new Float32Array(3);b[0]=a[0];b[1]=a[1];b[2]=a[2];return b}function jb(a,b){var c=a[0],d=a[1],e=a[2],c=1/Math.sqrt(c*c+d*d+e*e);b[0]=a[0]*c;b[1]=a[1]*c;b[2]=a[2]*c}function kb(a,b,c){var d=a[0],e=a[1],a=a[2],g=b[0],h=b[1],b=b[2];c[0]=e*b-a*h;c[1]=a*g-d*b;c[2]=d*h-e*g};function pb(a){var b=new Float32Array(4);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b}function qb(a,b,c,d){var e=new Float32Array(4);e[0]=a;e[1]=b;e[2]=c;e[3]=d;return e};function gb(){return new Float32Array(16)}function hb(a,b,c,d,e,g,h,m,l,o,r,s,z,A,u,w,t){a[0]=b;a[1]=c;a[2]=d;a[3]=e;a[4]=g;a[5]=h;a[6]=m;a[7]=l;a[8]=o;a[9]=r;a[10]=s;a[11]=z;a[12]=A;a[13]=u;a[14]=w;a[15]=t}function lb(a,b,c){a[b]=c[0];a[b+4]=c[1];a[b+8]=c[2];a[b+12]=c[3]}function rb(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}
function nb(a,b,c){var d=a[0],e=a[1],g=a[2],h=a[3],m=a[4],l=a[5],o=a[6],r=a[7],s=a[8],z=a[9],A=a[10],u=a[11],w=a[12],t=a[13],B=a[14],a=a[15],F=b[0],M=b[1],N=b[2],I=b[3],J=b[4],X=b[5],La=b[6],Ma=b[7],Na=b[8],Oa=b[9],Pa=b[10],Qa=b[11],Ra=b[12],Sa=b[13],Ta=b[14],b=b[15];c[0]=d*F+m*M+s*N+w*I;c[1]=e*F+l*M+z*N+t*I;c[2]=g*F+o*M+A*N+B*I;c[3]=h*F+r*M+u*N+a*I;c[4]=d*J+m*X+s*La+w*Ma;c[5]=e*J+l*X+z*La+t*Ma;c[6]=g*J+o*X+A*La+B*Ma;c[7]=h*J+r*X+u*La+a*Ma;c[8]=d*Na+m*Oa+s*Pa+w*Qa;c[9]=e*Na+l*Oa+z*Pa+t*Qa;c[10]=g*
Na+o*Oa+A*Pa+B*Qa;c[11]=h*Na+r*Oa+u*Pa+a*Qa;c[12]=d*Ra+m*Sa+s*Ta+w*b;c[13]=e*Ra+l*Sa+z*Ta+t*b;c[14]=g*Ra+o*Sa+A*Ta+B*b;c[15]=h*Ra+r*Sa+u*Ta+a*b}function sb(a,b,c){var d=b[0],e=b[1],b=b[2];c[0]=d*a[0]+e*a[4]+b*a[8]+a[12];c[1]=d*a[1]+e*a[5]+b*a[9]+a[13];c[2]=d*a[2]+e*a[6]+b*a[10]+a[14]}function mb(a,b,c,d){var e=a[1]*b+a[5]*c+a[9]*d+a[13],g=a[2]*b+a[6]*c+a[10]*d+a[14],h=a[3]*b+a[7]*c+a[11]*d+a[15];a[12]=a[0]*b+a[4]*c+a[8]*d+a[12];a[13]=e;a[14]=g;a[15]=h}new Float64Array(3);new Float64Array(3);
var ib=[new Float64Array(4),new Float64Array(4),new Float64Array(4)];new Float64Array(16);function S(a,b,c){this.type=b||P.STANDALONE;c&&(this.parent=c);this.children=[];this.e=T.DEFAULT;a&&this.O(a);this.type==P.STANDALONE&&this.Na([1,1,1,1]);if(y&&(!c||c.type!=P.BLOCKGROUP))this.k=C.createBuffer(),this.i=new Float32Array(36);this.c=gb();this.p=gb();this.c=rb(gb());this.ia=[];this.Q=[]}var T={DEFAULT:0,TEXTURE:1},tb=["default","texture"],P={STANDALONE:0,BLOCKGROUP:1,SCENE:2,TMXBLOCK:3,PARTICLE:4,PRIMITIVE:5},ub=Math.PI/180,vb=180/Math.PI,wb=1*ub,xb=qb(0,0,1,1),yb=new O(0,0);p=S.prototype;
p.title="";p.c=k;p.p=k;p.visible=j;p.f=n;p.D=n;p.F=n;p.W=0;p.k=k;p.i=k;p.position=new Float32Array(3);p.r=k;p.color=qb(1,1,1,1);p.b=k;p.opacity=1;p.rotation=0;p.scale=1;p.update=k;p.frame=k;p.parent=k;p.children=k;p.ia=k;p.Q=k;p.m=n;function zb(a){if(a.e==T.TEXTURE){var b=new U(1,1);a.B(b);b.Pa(function(){var a=this.parent.r,b=a.width/2,a=a.height/2;this.Ea([[-b,-a,0],[-b,a,0],[b,a,0],[b,-a,0]],[1,1,1,1],j)})}}
p.O=function(a){if("string"===typeof a){var b=V.Y(a),a=b.frame;this.T(b.b)}this.frame=pb(a);this.wa(a[2],a[3]);this.F=j};p.Y=aa("frame");p.wa=function(a,b){this.r=new O(a,b);this.F=j};p.cb=aa("r");p.lb=function(a){this.scale=a;this.f=j};p.fb=aa("scale");p.Na=function(a){this.color=pb(a);this.D=j};p.bb=aa("color");p.ea=function(a){this.position=ob(a);this.f=j};p.ab=function(){var a=this.position,b=this.frame[2],c=this.frame[3];return[a[0]-b/2,a[1]-c/2,b,c]};
p.T=function(a){this.b=a;this.e=T.TEXTURE;sa&&zb(this);var b=this;H("texture",a,function(a){b.r||b.wa(a.width,a.height);b.frame||b.O([0,0,a.width,a.height])})};p.gb=aa("b");p.eb=aa("rotation");p.Pa=function(a){this.update=a};p.mb=function(a){this.visible=a};p.ib=aa("visible");p.B=function(a){a.parent&&f("can't add a block twice!");this.m?this.ia.push(a):(this.children.push(a),a.parent=this)};
p.removeChild=function(a){(!a.parent||a.parent!=this)&&f("not our child!");this.m?this.Q.push(a):(a=this.children.indexOf(a),0<=a&&this.children.splice(a,1))};
p.transform=function(){var a=C;if(this.f||this.parent&&this.parent.f){this.c=rb(this.c);mb(this.c,this.position[0],this.position[1],this.position[2]);var b=this.c,c=-1*this.rotation,d=b[0],e=b[1],g=b[2],h=b[3],m=b[4],l=b[5],o=b[6],r=b[7],s=b[8],z=b[9],A=b[10],u=b[11],w=Math.cos(c),t=Math.sin(c),B=1-w,c=0*B+w,F=0*B+1*t,M=0*B-0*t,N=0*B-1*t,I=0*B+w,J=0*B+0*t,X=0*B+0*t,t=0*B-0*t,w=1*B+w;hb(b,d*c+m*F+s*M,e*c+l*F+z*M,g*c+o*F+A*M,h*c+r*F+u*M,d*N+m*I+s*J,e*N+l*I+z*J,g*N+o*I+A*J,h*N+r*I+u*J,d*X+m*t+s*w,e*
X+l*t+z*w,g*X+o*t+A*w,h*X+r*t+u*w,b[12],b[13],b[14],b[15]);b=this.c;e=d=this.scale;hb(b,b[0]*d,b[1]*d,b[2]*d,b[3]*d,b[4]*e,b[5]*e,b[6]*e,b[7]*e,1*b[8],1*b[9],1*b[10],1*b[11],b[12],b[13],b[14],b[15]);(b=this.parent?this.parent.c:k)&&nb(b,this.c,this.c)}if(!(this.type==P.BLOCKGROUP||this.type==P.PRIMITIVE))if(b=this.i,d=this.parent&&this.parent.type==P.BLOCKGROUP,y){!d&&(this.F||this.D)&&a.bindBuffer(a.ARRAY_BUFFER,this.k);if(this.F||d&&this.f)if(o=0.5*this.r.width,r=0.5*this.r.height,g=this.position[2],
e=36*this.W,d?(h=[o,r,0],m=[-o,r,0],l=[o,-r,0],o=[-o,-r,0],sb(this.c,h,h),sb(this.c,m,m),sb(this.c,o,o),sb(this.c,l,l),b[e]=o[0],b[e+1]=o[1],b[e+2]=g,b[e+9]=m[0],b[e+1+9]=m[1],b[e+2+9]=g,b[e+18]=l[0],b[e+1+18]=l[1],b[e+2+18]=g,b[e+27]=h[0],b[e+1+27]=h[1],b[e+2+27]=g):(b[e]=-o,b[e+1]=-r,b[e+2]=0,b[e+9]=-o,b[e+1+9]=r,b[e+2+9]=0,b[e+18]=o,b[e+1+18]=-r,b[e+2+18]=0,b[e+27]=o,b[e+1+27]=r,b[e+2+27]=0),this.e==T.TEXTURE)g=Ga("texture",this.b),m=g.width,l=g.height,g=this.frame[0]/m+0.0010,h=this.frame[1]/
l+0.0010,m=this.frame[2]/m-0.0020,l=this.frame[3]/l-0.0020,e+=3,b[e]=g,b[e+1]=h,b[e+9]=g,b[e+1+9]=h+l,b[e+18]=g+m,b[e+1+18]=h,b[e+27]=g+m,b[e+1+27]=h+l;if(this.D){e=5+36*this.W;g=this.color;h=this.opacity;for(m=0;4>m;m++)b[e+9*m]=g[0]*h,b[e+1+9*m]=g[1]*h,b[e+2+9*m]=g[2]*h,b[e+3+9*m]=g[3]*h}y&&(!d&&(this.F||this.D))&&a.bufferData(a.ARRAY_BUFFER,this.i,a.STATIC_DRAW)}};
p.A=function(){this.m=j;this.update&&this.update(wa);if(this.visible){this.transform();(!this.parent||this.parent.type!=P.BLOCKGROUP)&&this.N();for(var a=this.children,b=a.length,c=0;c<b;c++)a[c].A();for(this.m=this.F=this.D=this.f=n;a=this.ia.shift();)this.B(a);for(;a=this.Q.shift();)this.removeChild(a)}else this.m=n};
p.N=function(){this.type==P.BLOCKGROUP&&f("Cannot call render on a BlockGroup block!");if(this.type!=P.SCENE){var a,b;if(y){a=C;var c=za(tb[this.e]);a.bindBuffer(a.ARRAY_BUFFER,this.k);a.vertexAttribPointer(c.a.vertexPositionAttribute,3,a.FLOAT,n,36,0);a.vertexAttribPointer(c.a.vertexColorAttribute,4,a.FLOAT,n,36,20);this.e!=T.DEFAULT&&this.e==T.TEXTURE&&(b=Ga("texture",this.b),a.vertexAttribPointer(c.a.textureCoordAttribute,2,a.FLOAT,n,36,12),a.activeTexture(a.TEXTURE0),a.bindTexture(a.TEXTURE_2D,
b.U),a.uniform1i(c.ua,0));(this.f||this.parent&&this.parent.f)&&nb(qa,this.c,this.p);a.uniformMatrix4fv(c.u,n,this.p);a.drawArrays(a.TRIANGLE_STRIP,0,4)}else if(a=fa,1==this.e){c=this.c;b=Ga("texture",this.b);a.globalAlpha=this.opacity;a.setTransform(c[0],c[4],c[1],c[5],c[12],a.P-c[13]);var c=this.r.width,d=this.r.height,e=this.frame;a.drawImage(b,e[0],b.height-(e[1]+d),e[2],e[3],-c/2,-d/2,c,d)}}};q("chesterGL.Block",S);q("chesterGL.Block.FullFrame",xb);q("chesterGL.Block.SizeZero",yb);
q("chesterGL.Block.TYPE",P);q("chesterGL.Block.PROGRAM",T);q("chesterGL.Block.PROGRAM_NAME",tb);q("chesterGL.Block.DEG_TO_RAD",ub);q("chesterGL.Block.RAD_TO_DEG",vb);q("chesterGL.Block.ONE_DEG",wb);S.prototype.title=S.prototype.title;S.prototype.children=S.prototype.children;S.prototype.addChild=S.prototype.B;S.prototype.removeChild=S.prototype.removeChild;S.prototype.getBoundingBox=S.prototype.ab;S.prototype.setPosition=S.prototype.ea;S.prototype.getRotation=S.prototype.eb;S.prototype.setColor=S.prototype.Na;
S.prototype.getColor=S.prototype.bb;S.prototype.setFrame=S.prototype.O;S.prototype.getFrame=S.prototype.Y;S.prototype.setContentSize=S.prototype.wa;S.prototype.getContentSize=S.prototype.cb;S.prototype.setTexture=S.prototype.T;S.prototype.getTexture=S.prototype.gb;S.prototype.setScale=S.prototype.lb;S.prototype.getScale=S.prototype.fb;S.prototype.setUpdate=S.prototype.Pa;S.prototype.setVisible=S.prototype.mb;S.prototype.isVisible=S.prototype.ib;function Ab(a,b,c){var b=b||"20pt sans-serif",c=c||"White",d=document.createElement("canvas");this.canvas=d;this.context=d.getContext("2d");this.font=b;this.fillStyle=c;this.b=Date.now()+".canvas";D.texture||(D.texture={});D.texture[this.b]=d;S.call(this,Bb(this,a));this.Oa(a,j);this.e=T.TEXTURE}v(Ab,S);p=Ab.prototype;p.canvas=k;p.context=k;p.sa=n;p.text="";p.fa=0;p.font="";p.fillStyle="";p.Oa=function(a,b){this.text=a;b?Cb(this):(this.O(Bb(this)),this.sa=j)};
function Cb(a){var b=a.context,c=a.canvas;b.clearRect(0,0,c.width,c.height);b.fillText(a.text,0,0.8*c.height);Ia(a.b,c);a.sa=n}function Bb(a,b){var c=a.context,d=a.canvas;c.font=a.font;c.fillStyle=a.fillStyle;b&&(a.text=b);0===a.fa&&(c.save(),c.rotate(90),a.fa=1.25*c.measureText("M").width,c.restore());var e=c.measureText(a.text).width;d.width=e;d.height=a.fa;c.font=a.font;c.fillStyle=a.fillStyle;return[0,0,e,a.fa]}p.A=function(){this.sa&&Cb(this);S.prototype.A.call(this)};
q("chesterGL.LabelBlock",Ab);Ab.prototype.setText=Ab.prototype.Oa;function W(a,b){this.totalTime=a;this.g=b;this.j=0}p=W.prototype;p.I=0;p.g=k;p.totalTime=0;p.j=0;p.C=n;p.z=n;p.update=function(a){this.j+=a;0<this.totalTime&&this.j>=this.totalTime&&this.stop()};p.q=function(){this.z=j};p.stop=function(){this.C=j;this.z=n};p.reset=function(){this.C=this.z=n;this.j=0};function Y(a,b,c,d){W.call(this,b,d);this.X=ob(a);this.na=c!==i?c===j:j;this.R=new Float32Array(3)}v(Y,W);Y.prototype.X=k;Y.prototype.R=k;Y.prototype.na=j;Y.prototype.Ta=k;var Db=new Float32Array(3);
Y.prototype.update=function(a){W.prototype.update.call(this,a);var a=this.g,b=this.Ta,c=this.R,d=Math.min(1,this.j/this.totalTime),e=b[0],g=b[1],b=b[2];Db[0]=(c[0]-e)*d+e;Db[1]=(c[1]-g)*d+g;Db[2]=(c[2]-b)*d+b;a.ea(Db)};Y.prototype.q=function(){W.prototype.q.call(this);this.g||f("invalid move action! - no block");if(this.na){var a=this.X,b=this.g.position,c=this.R;c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2]}else this.R=this.X;this.Ta=this.g.position};
Y.prototype.stop=function(){W.prototype.stop.call(this);this.j>=this.totalTime&&this.g.ea(this.R)};Y.prototype.reverse=function(){this.na||f("This only works on relative movements");var a=[],b=this.X;a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];return new Y(a,this.totalTime,j)};function Eb(a,b){this.Aa=a;this.za=b;W.call(this,1)}v(Eb,W);Eb.prototype.Aa=k;Eb.prototype.za=k;Eb.prototype.update=function(a){this.Aa.call(k,this.za);W.prototype.update.call(this,a)};
function Fb(a,b){W.call(this,a.totalTime+b.totalTime);this.n=[a,b]}v(Fb,W);p=Fb.prototype;p.n=k;p.ka=0;p.Ra=0;p.q=function(){W.prototype.q.call(this);this.Ra=this.n[0].totalTime;this.g.da(this.n[0])};p.reset=function(){W.prototype.reset.call(this);this.ka=0;this.n[0].reset();this.n[1].reset();L.ga(this.n[0].I);L.ga(this.n[1].I)};p.update=function(a){W.prototype.update.call(this,a);0===this.ka&&this.j>=this.Ra&&(this.n[0].stop(),this.ka=1,this.g.da(this.n[1]))};
function Gb(a,b){this.ra=b||1;this.xa=0;this.action=a;W.call(this,a.totalTime)}v(Gb,W);p=Gb.prototype;p.ra=0;p.xa=0;p.action=k;p.q=function(){W.prototype.q.call(this);this.g.da(this.action)};p.update=function(a){W.prototype.update.call(this,a);if(this.C&&(0>this.ra||this.xa<this.ra))this.xa++,this.reset(),L.ga(this.action.I),this.action.reset(),this.q()};function Hb(a,b,c,d){this.delay=a;a*=b.length;c===j&&(a=-1);W.call(this,a,d);this.Qa=c===j;this.frames=b.slice(0)}v(Hb,W);p=Hb.prototype;p.J=0;
p.delay=0;p.frames=k;p.Qa=n;p.update=function(a){W.prototype.update.call(this,a);a=this.g;this.C?(this.J=this.frames.length-1,a.O(this.frames[this.J])):this.j>=this.delay*this.J&&(a.O(this.frames[this.J++]),this.J==this.frames.length&&(this.Qa?this.j=this.J=0:this.C=j))};function Ib(a,b,c,d){this.ya=a;this.Da=b;W.call(this,c,d)}v(Ib,W);Ib.prototype.ya=0;Ib.prototype.Da=0;
Ib.prototype.update=function(a){W.prototype.update.call(this,a);this.C?(a=this.g,a.rotation=0):(a=this.g,a.rotation=this.ya*Math.sin(2*(this.j/1E3*this.Da)*Math.PI/(this.totalTime/1E3)));a.f=j};
var L={H:[],va:[],hb:0,Ma:function(a){L.H.push(a);a.I=L.hb++;a.q();return a.I},ga:function(a){for(var b=L.H.length,c=0;c<b;c++){var d=L.H[c];if(d.I==a){L.va.push(d);break}}},nb:function(a){for(var b=0,c=L.H.length,d=k,b=0;b<c;b++)d=L.H[b],d.z&&d.update(a),d.C&&L.va.push(d);for(;d=L.va.pop();)a=L.H.indexOf(d),0<=a&&L.H.splice(a,1)}};S.prototype.da=function(a){a.g=this;L.Ma(a)};q("chesterGL.ActionManager",L);q("chesterGL.MoveAction",Y);q("chesterGL.CallbackAction",Eb);q("chesterGL.SequenceAction",Fb);
q("chesterGL.RepeatAction",Gb);q("chesterGL.AnimateAction",Hb);q("chesterGL.WiggleAction",Ib);L.scheduleAction=L.Ma;L.unscheduleAction=L.ga;Fb.createSequence=function(a){0===arguments.length&&f("Needs at least one action to create a sequence!");for(var b=arguments[0],c=1;c<arguments.length;c++)b=new Fb(b,arguments[c]);return b};S.prototype.runAction=S.prototype.da;W.prototype.stop=W.prototype.stop;Y.prototype.stop=Y.prototype.stop;Fb.prototype.stop=Fb.prototype.stop;Gb.prototype.stop=Gb.prototype.stop;
Y.prototype.reverse=Y.prototype.reverse;var V={frames:{},kb:function(a){if(a.meta&&"1.0"==a.meta.version){var b=a.meta.image;H("texture",b,function(c){var c=c.height,d=a.frames,e;for(e in d){var g=d[e],h={frame:{},b:""};h.frame=qb(g.frame.x,c-(g.frame.y+g.frame.h),g.frame.w,g.frame.h);h.b=b;V.frames[e]=h}})}else f("Unkown json data")},$a:function(a,b){D.frameset[a].data=b;return j},Y:function(a){return V.frames[a]},jb:function(a){console.log("loadFrames: will fetch "+a);H("frameset",{path:a,dataType:"json"},function(a){V.kb(a)})}};
E.frameset=V.$a;q("chesterGL.BlockFrames",V);V.getFrame=V.Y;V.loadFrames=V.jb;function U(a,b){y||f("PrimitiveBlock only works on WebGL mode");this.qa=a||500;this.pa=b||500;S.call(this,k,P.PRIMITIVE);var c=C;this.ma=c.createBuffer();this.o=new Float32Array(7*this.qa);this.la=c.createBuffer();this.d=new Float32Array(14*this.pa);this.e=T.DEFAULT}v(U,S);p=U.prototype;p.ma=k;p.o=k;p.la=k;p.d=k;p.pa=0;p.s=0;p.qa=0;p.t=0;p.M=[];
p.Za=function(a,b,c){if(this.t<this.qa){var d=7*this.t,c=c||[1,1,1,1];this.o[d+0]=a;this.o[d+1]=b;this.o[d+2]=0;this.o[d+3]=c[0];this.o[d+4]=c[1];this.o[d+5]=c[2];this.o[d+6]=c[3];this.t++}else f("too many points!")};
p.Ya=function(a,b,c,d,e){if(this.s<this.pa){var g=14*this.s,e=e||[1,1,1,1];this.d[g+0]=a;this.d[g+1]=b;this.d[g+2]=0;this.d[g+3]=e[0];this.d[g+4]=e[1];this.d[g+5]=e[2];this.d[g+6]=e[3];this.d[g+7]=c;this.d[g+8]=d;this.d[g+9]=0;this.d[g+10]=e[0];this.d[g+11]=e[1];this.d[g+12]=e[2];this.d[g+13]=e[3];this.s++}else f("too many lines!")};
p.Ea=function(a,b,c,d){for(var b=b||[1,1,1,1],c=c||n,d=d||n,e=a.length,g=C,h=new Float32Array(7*a.length),m=g.createBuffer(),l=0;l<e;l++){var o=a[l];h[7*l+0]=o[0];h[7*l+1]=o[1];h[7*l+2]=o[2];h[7*l+3]=b[0];h[7*l+4]=b[1];h[7*l+5]=b[2];h[7*l+6]=b[3]}g.bindBuffer(g.ARRAY_BUFFER,m);g.bufferData(g.ARRAY_BUFFER,h,g.STATIC_DRAW);this.M.unshift([h,m,c,d])};p.A=function(){this.s=this.t=0;0<this.M.length&&(this.M=[]);S.prototype.A.call(this)};
p.N=function(){var a=C,b=za(tb[this.e]);if(0<this.t||0<this.s||0<this.M.length)nb(qa,this.c,this.p),a.uniformMatrix4fv(b.u,n,this.p);if(0<this.t){var c=C,d=7*this.t;c.bindBuffer(c.ARRAY_BUFFER,this.ma);c.bufferData(c.ARRAY_BUFFER,this.o.subarray(0,d),c.STATIC_DRAW);a.bindBuffer(a.ARRAY_BUFFER,this.ma);a.vertexAttribPointer(b.a.vertexPositionAttribute,3,a.FLOAT,n,28,0);a.vertexAttribPointer(b.a.vertexColorAttribute,4,a.FLOAT,n,28,12);a.drawArrays(a.POINTS,0,this.t)}0<this.s&&(c=C,d=14*this.s,c.bindBuffer(c.ARRAY_BUFFER,
this.la),c.bufferData(c.ARRAY_BUFFER,this.d.subarray(0,d),c.STATIC_DRAW),a.bindBuffer(a.ARRAY_BUFFER,this.la),a.vertexAttribPointer(b.a.vertexPositionAttribute,3,a.FLOAT,n,28,0),a.vertexAttribPointer(b.a.vertexColorAttribute,4,a.FLOAT,n,28,12),a.drawArrays(a.LINES,0,2*this.s));c=this.M.length;if(0<c)for(d=0;d<c;d++){var e=this.M[d];a.bindBuffer(a.ARRAY_BUFFER,e[1]);a.vertexAttribPointer(b.a.vertexPositionAttribute,3,a.FLOAT,n,28,0);a.vertexAttribPointer(b.a.vertexColorAttribute,4,a.FLOAT,n,28,12);
e[2]?a.drawArrays(a.LINE_LOOP,0,e[0].length/7):a.drawArrays(a.LINE_STRIP,0,e[0].length/7)}};q("chesterGL.PrimitiveBlock",U);U.prototype.drawPoint=U.prototype.Za;U.prototype.drawLine=U.prototype.Ya;U.prototype.drawPolygon=U.prototype.Ea;var Jb,Kb,Lb,Mb;function Nb(){return ba.navigator?ba.navigator.userAgent:k}Mb=Lb=Kb=Jb=n;var Ob;if(Ob=Nb()){var Pb=ba.navigator;Jb=0==Ob.indexOf("Opera");Kb=!Jb&&-1!=Ob.indexOf("MSIE");Lb=!Jb&&-1!=Ob.indexOf("WebKit");Mb=!Jb&&!Lb&&"Gecko"==Pb.product}var Qb=Kb,Rb=Mb,Sb=Lb;var Tb;if(Jb&&ba.opera){var Ub=ba.opera.version;"function"==typeof Ub&&Ub()}else Rb?Tb=/rv\:([^\);]+)(\)|;)/:Qb?Tb=/MSIE\s+([^\);]+)(\)|;)/:Sb&&(Tb=/WebKit\/(\S+)/),Tb&&Tb.exec(Nb());var Vb=k,Wb=k;function Xb(a){(a=Yb[a])||f("Invalid map - make sure you call loadTMX first");S.call(this,k,P.TMXBLOCK);for(var b=0;b<a.layers.length;b++){for(var c=a.layers[b],d=y?new Z(k,c.blocks.length):new S,e=k,g=0;g<c.blocks.length;g++){var h=c.blocks[g];e||(e=Zb(a.tilesets,h.gid),d.T(e.texture));var m=i;y?m=d.Ca(h.frame):(m=new S(h.frame),m.T(e.texture));m.ea(h.position);d.B(m)}this.B(d)}}v(Xb,S);Xb.prototype.N=function(){};var Yb={};
function Zb(a,b){for(var c=a[0],d=1;d<a.length;d++){var e=a[d];b>=e.firstgid&&(c=e)}return c}E.tmx=function(a,b){D.tmx[a].data=b;return j};q("chesterGL.TMXBlock",Xb);
Xb.loadTMX=function(a){H("tmx",{path:a,dataType:"xml"},function(b){var c={},b=$(b).find("map"),d=b.attr("orientation");c.tilesets=[];b.find("tileset").each(function(a,b){var d=$(b);if("obstruction"!=d.attr("name")){var m={};m.tileSize=new O(parseInt(d.attr("tilewidth"),10),parseInt(d.attr("tileheight"),10));d.attr("spacing")&&(m.spacing=parseInt(d.attr("spacing"),10));d.attr("margin")&&(m.margin=parseInt(d.attr("margin"),10));var l=d.find("image").first();m.imgSize=new O(parseInt(l.attr("width"),
10),parseInt(l.attr("height"),10));m.texture=l.attr("source");m.firstgid=parseInt(d.attr("firstgid"),10);c.tilesets.push(m)}});c.mapTileSize=new O(parseInt(b.attr("tilewidth"),10),parseInt(b.attr("tileheight"),10));c.layers=[];b.find("layer").each(function(a,b){if("0"!=$(b).attr("visible")){var h={blocks:[]},m=new O(parseInt($(b).attr("width"),10),parseInt($(b).attr("height"),10)),l=$(b).find("data").first();if(l){("base64"!=l.attr("encoding")||l.attr("compression"))&&f("Invalid TMX Data");var o=
l.text().trim();if(!Vb){Vb={};Wb={};for(l=0;65>l;l++)Vb[l]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(l),Wb[Vb[l]]=l}for(var r=Wb,l=[],s=0;s<o.length;){var z=r[o.charAt(s++)],A=s<o.length?r[o.charAt(s)]:0;++s;var u=s<o.length?r[o.charAt(s)]:0;++s;var w=s<o.length?r[o.charAt(s)]:0;++s;(z==k||A==k||u==k||w==k)&&f(Error());l.push(z<<2|A>>4);64!=u&&(l.push(A<<4&240|u>>2),64!=w&&l.push(u<<6&192|w))}o=0;r=k;for(s=0;s<m.height;s++)for(z=0;z<m.width;z++){var t=l[o+3]<<24|l[o+
2]<<16|l[o+1]<<8|l[o+0]>>>0;if(0!=t){r||(r=Zb(c.tilesets,t));A={};A.gid=t;var B=r.margin||0,F=r.spacing||0,u=r.tileSize,M=r.imgSize,w=c.mapTileSize,N=parseInt((M.width-2*B+F)/(u.width+F),10),t=t-r.firstgid,t=qb(t%N*(u.width+F)+B,M.height-u.height-B-F-parseInt(t/N,10)*(u.height+F)+B,u.width,u.height);A.frame=t;var I,J;"orthogonal"==d?(I=z*w.width+u.width/2,J=(m.height-s-1)*w.height+u.height/2):"isometric"==d?(I=w.width/2*(m.width+z-s-1)+u.width/2,J=w.height/2*(2*m.height-z-s-2)+u.height/2):f("Invalid orientation");
A.position=[I,J,0];h.blocks.push(A)}o+=4}}else f("No data for layer!");c.layers.push(h)}});Yb[a]=c})};function $b(a){S.call(this,k,4);var b=this;H("texture",a.texture,function(){b.Ka(a)})}v($b,S);var ac=n;
function bc(){Da("particles",function(a){var b=C;a.u=b.getUniformLocation(a,"uMVPMatrix");a.ob=b.getUniformLocation(a,"uSampler");a.rb=b.getUniformLocation(a,"u_time");a.qb=b.getUniformLocation(a,"u_startColor");a.pb=b.getUniformLocation(a,"u_endColor");a.a={a_startPosition:b.getAttribLocation(a,"a_startPosition"),a_lifetime:b.getAttribLocation(a,"a_lifetime"),a_startTime:b.getAttribLocation(a,"a_startTime"),a_startSize:b.getAttribLocation(a,"a_startSize"),a_endSize:b.getAttribLocation(a,"a_endSize"),
a_speed:b.getAttribLocation(a,"a_speed")};a=b.getError();0!=a&&console.log("gl error: "+a)});ac=j}p=$b.prototype;p.z=j;p.La=k;p.Fa=0;p.K=0;p.v=0;p.G=0;p.duration=0;p.oa=0;p.Ja=0;p.Sa=k;p.ca=k;p.Ga=k;p.aa=k;p.ba=k;p.Ua=0;p.Va=0;p.Ha=0;p.Ia=0;p.ta=n;p.elapsedTime=0;p.ja=["SRC_ALPHA","ONE_MINUS_SRC_ALPHA"];
p.Ka=function(a){this.e=-1;ac||bc();this.La=a.texture;this.G=a.maxParticles;this.duration=1E3*parseFloat(a.duration);this.oa=1E3*parseFloat(a.lifetime);this.Ja=1E3*parseFloat(a.lifetimeVariance);this.Sa=pb(a.startColor);this.ca=ob(a.positionVariance);this.Ga=pb(a.endColor);this.aa=ob(a.speed);this.ba=ob(a.speedVariance);this.Ua=parseFloat(a.startSize);this.Va=parseFloat(a.startSizeVariance);this.Ha=parseFloat(a.endSize);this.Ia=parseFloat(a.endSizeVariance);this.elapsedTime=0;this.ja=a.blendOptions.slice(0);
this.z=j;this.k=C.createBuffer();this.i=new Float32Array(10*this.G);for(var a=za("particles"),b=C,c=0;c<this.G;c++)cc(this,c);b.uniform4fv(a.qb,this.Sa);b.uniform4fv(a.pb,this.Ga);b.uniform1i(a.ob,0);dc(this);this.v=this.K=0;this.Fa=this.G/Math.abs(this.oa)};
function cc(a,b,c,d){var e=a.i;e[10*b+0]=c||-1;e[10*b+1]=d||0;e[10*b+2]=a.Ua+a.Va*(2*Math.random()-1);e[10*b+3]=a.Ha+a.Ia*(2*Math.random()-1);e[10*b+4]=a.aa[0]+a.ba[0]*(2*Math.random()-1);e[10*b+5]=a.aa[1]+a.ba[1]*(2*Math.random()-1);e[10*b+6]=a.aa[2]+a.ba[2]*(2*Math.random()-1);e[10*b+7]=(2*Math.random()-1)*a.ca[0];e[10*b+8]=(2*Math.random()-1)*a.ca[1];e[10*b+9]=(2*Math.random()-1)*a.ca[2]}function dc(a){var b=C;b.bindBuffer(b.ARRAY_BUFFER,a.k);b.bufferData(b.ARRAY_BUFFER,a.i,b.STATIC_DRAW)}
var ec=new Float32Array(10);
$b.prototype.update=function(a){if(za("particles")){this.elapsedTime+=a;var b=1/this.Fa;for(this.K+=a;this.v<this.G&&this.K>b&&this.z;)cc(this,this.v,Math.abs(this.oa+this.Ja*(2*Math.random()-1)),this.elapsedTime),this.v++,this.ta=j,this.K-=b;for(a=0;a<this.G;a++){var b=this.i,c=10*a;if(0<b[c]&&b[c]+b[c+1]<=this.elapsedTime&&a!=this.v-1){var d=b.subarray(c,c+10);ec.set(d);ec[0]=-1;d=b.subarray(c+10,10*this.v);b.set(d,c);b.set(ec,10*(this.v-1));this.v--}}0<this.duration&&this.elapsedTime>this.duration&&
(this.z=n)}};
$b.prototype.N=function(){var a=za("particles");if(a){var b=C,c=Ga("texture",this.La);b.enable(b.BLEND);b.blendFunc(b[this.ja[0]],b[this.ja[1]]);this.ta&&(dc(this),this.ta=n);b.uniform1f(a.rb,this.elapsedTime);b.activeTexture(b.TEXTURE0);b.bindTexture(b.TEXTURE_2D,c.U);b.bindBuffer(b.ARRAY_BUFFER,this.k);b.vertexAttribPointer(a.a.a_lifetime,3,b.FLOAT,n,40,0);b.vertexAttribPointer(a.a.a_startTime,3,b.FLOAT,n,40,4);b.vertexAttribPointer(a.a.a_startSize,3,b.FLOAT,n,40,8);b.vertexAttribPointer(a.a.a_endSize,3,
b.FLOAT,n,40,12);b.vertexAttribPointer(a.a.a_speed,3,b.FLOAT,n,40,16);b.vertexAttribPointer(a.a.a_startPosition,3,b.FLOAT,n,40,28);(this.f||this.parent&&this.parent.f)&&nb(qa,this.c,this.p);b.uniformMatrix4fv(a.u,n,this.p);b.drawArrays(b.POINTS,0,this.G)}};q("chesterGL.ParticleSystem",$b);$b.loadShaders=bc;$b.prototype.loadProperties=$b.prototype.Ka;function Z(a,b){y||f("BlockGroup only works on WebGL mode");S.call(this,k,P.BLOCKGROUP);a?(this.b=a,this.e=T.TEXTURE):this.e=T.DEFAULT;this.L=b||10;fc(this)}v(Z,S);p=Z.prototype;p.L=0;p.$=n;p.Z=k;p.l=k;function fc(a,b,c){var d=C;a.k||(a.k=d.createBuffer());a.Z||(a.Z=d.createBuffer());var d=new Float32Array(36*a.L),e=new Uint16Array(6*a.L);b&&d.set(b);c&&e.set(c);a.i=d;a.l=e}p.Ca=function(a){a=new S(a,P.STANDALONE,this);this.b&&a.T(this.b);return a};
p.B=function(a){a.parent!=this&&f("Invalid child: can only add children created with BlockGroup.create");this.children.length>=this.L&&(this.L*=2,fc(this,this.i,this.l));this.b?this.b!=a.b&&f("Invalid child: only can add child with the same texture"):this.b=a.b;this.children.push(a);a.W=this.children.length-1;a.i=this.i;this.$=j};
p.removeChild=function(a){a.parent!=this&&f("Invalid child");if(this.m)this.Q.push(a);else{a=this.children.indexOf(a);if(0<a)for(this.children.splice(a,1);a<this.zb;a++){var b=this.children[a];b.W=a;b.f=j;b.D=j}this.$=j}};
p.A=function(){this.m=j;this.update&&this.update(wa);if(this.visible){this.transform();for(var a=this.children,b=a.length,c=0;c<b;c++)a[c].A();a=C;a.bindBuffer(a.ARRAY_BUFFER,this.k);a.bufferData(a.ARRAY_BUFFER,this.i,a.STATIC_DRAW);if(this.$){a=(this.l[-1]||-1)+1;b=Math.max(this.children.length,1);for(c=0;c<b;c++){var d=6*c;this.l[d+0]=a;this.l[d+1]=a+1;this.l[d+2]=a+2;this.l[d+3]=a+2;this.l[d+4]=a+1;this.l[d+5]=a+3;a+=4}a=C;a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,this.Z);a.bufferData(a.ELEMENT_ARRAY_BUFFER,
this.l,a.STATIC_DRAW);this.$=n}this.N();for(this.m=this.F=this.D=this.f=n;a=this.Q.shift();)this.removeChild(a)}else this.m=n};
p.N=function(){var a=C,b=za(tb[this.e]),c=this.children.length;a.bindBuffer(a.ARRAY_BUFFER,this.k);a.vertexAttribPointer(b.a.vertexPositionAttribute,3,a.FLOAT,n,36,0);if(this.e!=T.DEFAULT&&this.e==T.TEXTURE){var d=Ga("texture",this.b);a.vertexAttribPointer(b.a.textureCoordAttribute,2,a.FLOAT,n,36,12);a.activeTexture(a.TEXTURE0);a.bindTexture(a.TEXTURE_2D,d.U);a.uniform1i(b.ua,0)}a.vertexAttribPointer(b.a.vertexColorAttribute,4,a.FLOAT,n,36,20);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,this.Z);nb(qa,this.c,
this.p);a.uniformMatrix4fv(b.u,n,this.p);a.drawElements(a.TRIANGLES,6*c,a.UNSIGNED_SHORT,0)};q("chesterGL.BlockGroup",Z);Z.prototype.createBlock=Z.prototype.Ca;Z.prototype.addChild=Z.prototype.B;Z.prototype.removeChild=Z.prototype.removeChild;
